# Publish new GitHub release on PyPI.
name: Publish release

on: [workflow_dispatch]

jobs:

  publish:
      if: startsWith(github.ref, "refs/tags/")         # Commit must be tagged.
      runs-on: ubuntu-latest
      steps:

        - name: Check out code.
          uses: actions/checkout@v4

        - name: Install Python.
          uses: actions/setup-python@v5

        - name: Install UV.
          uses: astral-sh/setup-uv@v5

        - name: Build wheel.
          run:  uv build --wheel

        - name: Publish to PyPI.
          uses: pypa/gh-action-pypi-publish@release/v1
