name: Test commit

on: [push, pull_request, workflow_dispatch]

jobs:

    test:
        strategy:
            matrix:
                python: ["3.6", "3.11"]
        runs-on: ubuntu-20.04
        steps:

          - name: Check out code.
            uses: actions/checkout@v4

          - name: Install Python ${{ matrix.python }}.
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python }}

          - name: Install UV.
            uses: astral-sh/setup-uv@v5
            with:
                enable-cache: true
                cache-dependency-glob: "uv.lock"

          - name: Install package.
            run:  uv sync

          - name: Run test suite.
            run:  uv run pytest

          - name: Lint code.
            run:  uv run ruff check

          - name: Build package.
            run:  uv build --wheel --out-dir build/wheel

          - name: Render docs.
            run:  uv run sphinx-build docs build/docs
